apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels: {{ - include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: metrics
      port: {{ .Values.service.port }} # même port que http
      targetPort: http # même targetPort
      protocol: TCP
  selector: {{ - include "mychart.selectorLabels" . | nindent 4 }}
