name: elections-service

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chargement de repos
        uses: actions/checkout@v6
      - name: Mise en place de l'enironnement python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"
      - name: Installer les dependances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executer les tests
        run: pytest
